### ISSUE TITLE
Bug ricerca per intervallo di date

### ISSUE THREAD

**Issue by V4l3nt1n4** [Albertus82/EarthquakeBulletin#1]
Ciao!
Effettuando una ricerca per un intervallo di date, vengono visualizzate record che non ricadono nell'intervallo selezionato. Vedi figura:
![geofon](https://cloud.githubusercontent.com/assets/9019367/24407093/35a40244-13ca-11e7-8edb-32a57230344f.PNG)

**Comment by Albertus82** [comment]
Il problema deriva dal fatto che la data mostrata nella tabella è riferita al **fuso orario del sistema su cui viene utilizzato il programma**, mentre le date presenti nel form di ricerca si riferiscono sempre all'UTC e non accettano l'ora. Una possibile soluzione potrebbe essere quella di aggiungere nelle preferenze un'opzione che consenta di scegliere il fuso orario a cui riferire le date presenti nella tabella dei risultati della ricerca. Quale valore predefinito debba avere questa opzione è ancora da decidere ma propenderei per UTC.

**Comment by V4l3nt1n4** [comment]
Thank you!
